version: '4'
services:
  top-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: top-api:latest
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
